<?php

use App\Support\SpecialistCatalog;

/**
 * Catalog of specialists for the patient “Available specialists” page.
 * Entries reference `specialities.id` in `speciality_ids` (see SpecialistCatalog).
 *
 * @see SpecialistCatalog
 */
return [
    'entries' => [
        [
            'id' => 'nada-alghamdi',
            'name' => 'Nada Alghamdi',
            'name_ar' => 'ندى الغامدي',
            'specialist_role' => 'psychologist_non_md',
            'gender' => 'female',
            'languages' => ['ar', 'en'],
            'session_minutes' => 15,
            'speciality_ids' => [1, 2, 3],
            'likes' => 17,
            'price_sar' => 100,
            'bio' => 'Psychologist specialising in addictions and interpersonal challenges. Passionate about providing safe, evidenced-based interventions for adolescents and adults. Focus on supporting goals with sustainable habits and emotional regulation.',
            'bio_ar' => 'أخصائية نفسية بتركيز على الإدمان والعلاقات. تهتم بتقديم تدخلات آمنة مبنية على الأدلة للمراهقين والبالغين، مع تمكين انظباط الانفعال وبناء أهداف واقعية طويلة الأمد.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => false],
            'slots' => ['17:30', '17:45', '18:00', '18:15', '18:30', '18:45', '19:00'],
        ],
        [
            'id' => 'khalid-mohammed',
            'name' => 'Dr. Khalid Mohammed',
            'name_ar' => 'د. خالد محمد',
            'specialist_role' => 'psychiatrist',
            'gender' => 'male',
            'languages' => ['ar', 'en'],
            'session_minutes' => 15,
            'speciality_ids' => [8, 22, 16],
            'likes' => 40,
            'price_sar' => 150,
            'bio' => 'Psychiatrist focusing on anxiety, mood episodes, and short-term psychotherapy integrated with pharmacotherapy when clinically appropriate.',
            'bio_ar' => 'طبيب نفسي يركز على القلق واضطرابات المزاج، مع توفير علاج دوائي عند اللزوم ومتابعة مختصرة للعلاج النفسي.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => true],
            'slots' => ['09:30', '10:00', '10:30', '11:00', '17:30', '18:00'],
        ],
        [
            'id' => 'sara-hassan',
            'name' => 'Dr. Sara Hassan',
            'name_ar' => 'د. سارة حسن',
            'specialist_role' => 'consultant',
            'gender' => 'female',
            'languages' => ['en'],
            'session_minutes' => 30,
            'speciality_ids' => [17, 23],
            'likes' => 24,
            'price_sar' => 200,
            'bio' => 'Psychiatric consultant for complex presentations and care coordination, with a focus on anxiety and high stress.',
            'bio_ar' => 'استشارية نفسية للحالات المعقدة وتنسيق الرعاية، بتركيز على القلق والضغط النفسي الشديد.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => true],
            'slots' => ['12:00', '12:30', '13:00', '16:00', '16:30'],
        ],
        [
            'id' => 'omar-faisal',
            'name' => 'Dr. Omar Faisal',
            'name_ar' => 'د. عمر فيصل',
            'specialist_role' => 'psychiatrist',
            'gender' => 'male',
            'languages' => ['ar'],
            'session_minutes' => 45,
            'speciality_ids' => [16, 17],
            'likes' => 33,
            'price_sar' => 160,
            'bio' => 'Psychiatrist emphasising Arabic-language therapy and pharmacotherapy for mood and anxiety disorders.',
            'bio_ar' => 'طبيب نفسي يركز على العلاج باللغة العربية والعلاج الدوائي لاضطرابات المزاج والقلق.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => false],
            'slots' => ['08:00', '08:30', '09:00', '14:00', '14:30'],
        ],
        [
            'id' => 'fatima-noor',
            'name' => 'Dr. Fatima Noor',
            'name_ar' => 'د. فاطمة نور',
            'specialist_role' => 'psychiatrist',
            'gender' => 'female',
            'languages' => ['ar', 'en'],
            'session_minutes' => 30,
            'speciality_ids' => [16, 17, 8],
            'likes' => 52,
            'price_sar' => 175,
            'bio' => 'Psychiatrist working with adults on depression, anxiety, and panic, combining therapy orientation with medication when indicated.',
            'bio_ar' => 'طبيبة نفسية للبالغين في الاكتئاب والقلق والهلع، تجمع بين التوجيه العلاجي والدواء عند الحاجة.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => true],
            'slots' => ['10:00', '10:30', '11:00', '15:00', '15:30', '16:00'],
        ],
        [
            'id' => 'layla-ibrahim',
            'name' => 'Layla Ibrahim',
            'name_ar' => 'ليلى إبراهيم',
            'specialist_role' => 'psychologist_non_md',
            'gender' => 'female',
            'languages' => ['ar', 'en'],
            'session_minutes' => 60,
            'speciality_ids' => [25, 17],
            'likes' => 19,
            'price_sar' => 120,
            'bio' => 'Psychologist with a trauma-informed approach for PTSD and anxiety, using structured CBT techniques.',
            'bio_ar' => 'أخصائية نفسية بمنهج يراعي الصدمات لاضطراب ما بعد الصدمة والقلق، باستخدام تقنيات سلوكية معرفية منظمة.',
            'channels' => ['chat' => true, 'video' => true, 'voice' => true],
            'slots' => ['13:00', '13:30', '14:00', '18:00', '18:30', '19:00'],
        ],
    ],
];
